name: Deploy

on:
  push:
    branches:
      - master

env:
  CI: true
  BASE_PATH: /recipes

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build Static
        run: yarn export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
